<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cef_form_views_exposed_form_alter(&$form, &$form_state) {
  $dependencies = conditional_fields_load_data(array_shift($form_state['view']->filter['type']->value));
  $map = array();
  foreach ($form_state['view']->filter as $id => $handler) {
    if ($handler->is_exposed()) {
      if (isset($handler->definition['content_field_name'])) {
        $map[$handler->definition['content_field_name']] = $handler->field;
      }
    }
  }
  $dependencies_map = array();
  foreach ($dependencies as $depend) {
    if (isset($map[$depend['field_name']])) {
      $dependencies_map[$map[$depend['control_field_name']]][$map[$depend['field_name']]] = $depend['trigger_values'];
    }
  }
  drupal_add_js(drupal_get_path('module', 'cef') . '/cef.js');
  drupal_add_js(array('cef' => $dependencies_map), 'setting');
}

