<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cef_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  $dependencies = conditional_fields_load_dependencies($form_state['view']->base_table, array_shift($form_state['view']->filter['type']->value));
  $map = array();
  foreach ($form_state['view']->filter as $id => $handler) {
    if ($handler->can_expose() && $handler->is_exposed()) {
      if (isset($handler->definition['field_name'])) {
        $map[$handler->definition['field_name']] = $id;
      }
    }
  }
  $dependencies_map = array();
  foreach ($dependencies as $id => $depend) {
    if (isset($depend['dependents'])) {
      foreach ($depend['dependents'] as $fname => $farray) {
        if (isset($map[$fname])) {
          switch ($farray['options']['values_set']) {
            case '1':
              $values = array($farray['options']['value_form']);
              break;

            case '3':
              $values = $farray['options']['values'];
              break;
          }
          $dependencies_map[$map[$id]][$map[$fname]] = $values;
        }
      }
    }
  }
  drupal_add_js(drupal_get_path('module', 'cef') . '/cef.js');
  drupal_add_js(array('cef' => $dependencies_map), 'setting');
}

/**
 * Implements hook_field_attach_form().
 */
function cef_field_attach_form($entity_type, $entity, &$form, &$form_state, $langcode) {
  if (!$dependencies = conditional_fields_load_dependencies($entity_type, $form['#bundle'])) {
    return;
  }
  if (!$langcode) {
    $langcode = LANGUAGE_NONE;
  }
  foreach ($dependencies as $dependent => $dependency) {
    if (isset($dependency['dependees'])) {
      $form[$dependent][$langcode]['#options']['_none'] = $form[$dependent][$langcode]['#title'];
      $form[$dependent][$langcode]['#title'] = '';
      $form[$dependent]['#attributes']['class'][] = 'field-dependent';
    }
  }
}



